# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

# Mod
mod_id=maidcuriosmanager
mod_name=Maid Curios Manager
mod_group_id=com.maidcurios
mod_version=1.2.0
mod_authors=Bubble
mod_license=MIT

# Minecraft / Forge
minecraft_version=1.20.1
forge_version=47.4.0
loading_mod_loader=forge
mapping_channel=official
mapping_version=1.20.1

# Dependency ranges
minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)
loader_version_range=[47,)